package day58_exceptions_recap;

public class TryWithInheritance {
    public static void main(String[] args) {
        try {

        }catch (RuntimeException e){

        }catch (Exception e){}
    }
}
